### ISSUE TITLE
Remove Alternative instance

### ISSUE THREAD

**Issue by Avaq** [fluture-js/concurrify#3]
It never sat well with me that we pass `zero` and `alt` *into* `concurrify`, only to get back an object which does nothing more than dispatch to them. An author can just as easily call `concurrify` and then put their `zero` and `alt` on the prototype of its result. This leads me to conclude it might not be this library's responsibility to provide an Alternative instance. This was further reinforced when I realized a Monad can also have Alternative (see fluture-js/Fluture#89).

ping @safareli

**Comment by safareli** [comment]
If structure is monad then it could  potentially be `Monad{Plus,Or,Zero}` with sequential semantics and Alternative in that case would be derived from corresponding instance, in which case one might want to have different alternative instance for concurrent version. (same argument for `Fluture#89` if then want to make it `Monad*` then the alternative instance you proposed might not be valid.)

**Comment by Avaq** [comment]
Not going to move forward with this idea for now.

**Comment by Avaq** [comment]
I'm going to remove the hard requirement for Alternative instance from Concurrify. A user will only need to pass in concurrent `ap`. I'm doing this because I need it for another project I'm working on.

**Comment by Avaq** [comment]
On closer inspection, I'm going to leave this library as-is, and create something else after all.
