### ISSUE TITLE
TransformError: Couldn't find preset "latest" relative to directory 

### ISSUE THREAD

**Issue by stevenyap** [fluture-js/concurrify#4]
Hi,

I have an error when I run my code which is

`TransformError: /Users/aaa/Workspace/bbb/mobile/node_modules/concurrify/index.js: Couldn't find preset "latest" relative to directory "/Users/aaa/Workspace/bbb/mobile/node_modules/concurrify"`

Removing .babelrc in the concurrify folder will solve the problem.
NB: I am in React Native environment.

Any reason for this issue?

**Comment by Avaq** [comment]
Oh dear. The `.babelrc` must've slipped in when I copied the package structure from another project - likely Fluture. I'll remove it and release a patch.

**Comment by stevenyap** [comment]
Great! I thought it is due to my local babel misconfiguration or something. 👍
